// 渠晦

using System.Collections;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class InitCtrl : MonoBehaviour
{
    [Header("Add")]
    [SerializeField] private Button _initButton;
    [SerializeField] private TextMeshProUGUI _initText;
    private Coroutine _resetCallbackRoutine = null;
    [SerializeField] private int _successToBackTime = 10;

    [Header("Setting Component")]
    [SerializeField] private PhotoFrameSelectCtrl _photoFrameSelectCtrl;
    [SerializeField] private PrintController _printController;
    [SerializeField] private FadeAnimationCtrl _fadeAnimationCtrl;
    [SerializeField] private PrintButtonHandler _printButtonHandler;
    [SerializeField] private StepCountdownUI _stepCountdownUI;
    [SerializeField] private FilmingToSelectCtrl _filmingToSelectCtrl;
    [SerializeField] private FilmingEndCtrl _filmingEndCtrl;

    [Header("Setting Object")]
    [SerializeField] private Button _photoButton;
    [SerializeField] private GameObject _photoButtonFake;
    [SerializeField] private Image _photoImage;
    [SerializeField] private TextMeshProUGUI _buttonText;
    private ColorBlock _originColor;
    [Space(10)]
    [SerializeField] private GameObject _currentPanel;  // ⑷營 檣潑 諫猿  ぬ割
    [SerializeField] private GameObject _changePanel;   // 羹檣雖 腆 ぬ割 (⑷營 唸薯 ぬ割歜)
    [SerializeField] private GameObject _cameraFocus;   // 蘋詭塭 褻遽薄

    [Header("Filming")]
    [SerializeField] private GameObject _stepsObject;   // 1~5 蝶變 
    [SerializeField] private string _takePictureString = "餌霞鎰晦";
    [SerializeField] private TextMeshProUGUI _exitMessageText;
    [SerializeField, TextArea(4, 5)]
    private string _exitMessageString = "餌霞 譎艙檜 謙猿腎歷蝗棲棻.\n餌霞擊 轎溘ж撮蹂.";

    [SerializeField] private GameObject _exitMessage;

    [SerializeField] private GameObject[] _photoNumberObjs;
    [SerializeField] private TextMeshProUGUI _missionText;

    [Header("Test")]
    [SerializeField] private GameObject _startFilming;
    [SerializeField] private GameObject _endFilming;
    [SerializeField] private Button _endFilimgButton;       

    [SerializeField] private GameObject _filimgObject;           // 譎艙 醞 幗が 螃粽薛お
    [SerializeField] private GameObject _finishedFilimgObject;   // 譎艙 部 幗が 螃粽薛お
    [SerializeField] private Image _progressFillImage;

#pragma warning disable CS0414
    [Range(1f, 10f)]
    [Header("TimeScale Value")]
    [Tooltip("晦獄 : 1, 詢蝶 : 10")]
    [SerializeField] private float _timeScale = 1.0f;
#pragma warning disable CS0414

    private void Awake()
    {
        // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
        // Test 樓紫 隸陛
        Time.timeScale = 1f;
        // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式

        _initButton.onClick.AddListener(ResetManager);
        _originColor = _photoButton.colors;
    }
    
    /// <summary>
    /// 綠側瘓 腆 陽 公 賅蒂 囀瑞ず 褒ч 寞雖
    /// </summary>
    private void OnDisable()
    {
        if (_resetCallbackRoutine != null)
        {
            StopCoroutine(_resetCallbackRoutine);
            _resetCallbackRoutine = null;
        }
    }

    /// <summary>
    /// だ惚腆 陽 公 賅蒂 囀瑞ず 褒ч 寞雖? 寞橫辨檣等 だ惚腆 橾擎 橈擊蛭
    /// </summary>
    private void OnDestroy()
    {
        if (_resetCallbackRoutine != null)
        {
            StopCoroutine(_resetCallbackRoutine);
            _resetCallbackRoutine = null;
        }
    }

    // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式 幗が 贗葛 寰ц擊陽 轎 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
    // ⑷營 180蟾 翕寰 "給嬴陛晦" 幗が擊 贗葛ж雖 彊戲賊, 濠翕戲煎 蟾晦 飛橉虞 腎給嬴馬
    public void ResetCallBack()
    {        
        //print("111");
        if (_resetCallbackRoutine != null)
        {
            //print("222");
            StopCoroutine(_resetCallbackRoutine);
            _resetCallbackRoutine = null;
            // 臢蝶お紫 蟾晦            
        }        
        _resetCallbackRoutine = StartCoroutine(ResetCallBackCoroutine());
    }

    private IEnumerator ResetCallBackCoroutine()
    {        
        for (int i = _successToBackTime; i >= 1; i--)
        {
            if (_initText != null)
                _initText.text = $"{i}\n給嬴陛晦";

            yield return new WaitForSeconds(1f);
        }

        //print("式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式");
        //print("幗が 贗葛 寰ж賊 瞰渠 褒ч 寰腋撿л ...");
        //print("奩渠煎 幗が 贗葛 寰ж賊 褒ч腋撿ж雖 жжжжжжжжъж勻ж勻ж勻ж勻жъж");
        //print("式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式");

        ResetManager();        
    }
    // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式  
    // 仄仄
    /// <summary>
    /// 葬撢 識 婦葬濠
    /// </summary>
    private void ResetManager()
    {
        if (_resetCallbackRoutine != null)
        {
            StopCoroutine(_resetCallbackRoutine);
            _resetCallbackRoutine = null;
        }

        // 囀瑞ず擎 蟾晦
        _resetCallbackRoutine = null;

        // 臢蝶お紫 蟾晦
        if (_initText != null)
            _initText.text = "5\n給嬴陛晦";

        SoundManager.Instance.PlaySFX(SoundManager.Instance._soundDatabase._outputSuccess);
        _fadeAnimationCtrl.StartFade();
        // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
        FrameSelectReset();     // Щ溯歜 婦溼 葬撢
        FilmingPanelReset();    // 譎艙 ぬ割 婦溼 葬撢
        CaptureReset();         // 譫籀 婦溼 葬撢
        PrintHandlerReset();    // с菟楝 婦溼 葬撢
        PrintReset();           // Щ萼お 婦溼 葬撢        
        // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
        ButtonReset();          // 幗が 婦溼 葬撢 : 匐饜 в蹂
    }

    /// <summary>
    /// Щ溯歜 摹鷗 婦溼 葬撢
    /// </summary>
    private void FrameSelectReset()
    {
        _photoFrameSelectCtrl.AllReset();
    }

    /// <summary>
    /// 譎艙 ぬ割 婦溼 葬撢
    /// </summary>
    private void FilmingPanelReset()
    {
        _stepsObject.SetActive(true);

        _photoButton.colors = _originColor;
        _buttonText.color = Color.black;
        _buttonText.text = _takePictureString;

        _photoButtonFake.SetActive(false);

        _exitMessageText.text = _exitMessageString;
        _exitMessage.SetActive(false);

        _cameraFocus.SetActive(true);

        // 嘐暮 臢蝶お 蘋遴お 蟾晦
        _stepCountdownUI._missionCount = 0;
        // 嘐暮 臢蝶お 蟾晦
        _missionText.text = "";

        // ん饜 > (綠側瘓 腎湍 煎霜 剩幗 檜嘐雖 棻衛 側瘓)
        foreach (var item in _photoNumberObjs)
        {
            item.SetActive(true);
        }
    }

    /// <summary>
    /// 譫籀 婦溼 葬撢
    /// </summary>
    private void CaptureReset()
    {
        _stepCountdownUI.ResetSequence();
    }

    /// <summary>
    /// Щ萼お с菟楝 婦溼 葬撢
    /// ⑷營) 轎溘醞 -> 轎溘ж晦 幗が擊 贗葛ж雖 彊懊擊 陽 濠翕戲煎 剩橫陛晦 嬪и 撮た 蟾晦
    /// </summary>
    private void PrintHandlerReset()
    {
        _printButtonHandler.ResetPrintButtonHandler();
    }

    /// <summary>
    /// Щ萼お 葬撢 婦溼
    /// </summary>
    private void PrintReset()
    {
        _printController.ResetPrintState();
    }

    /// <summary>
    /// 蟾晦 й 幗が 婦溼
    /// 蘋詭塭 橈朝 婦溼戲煎 歜衛 纔蝶お 霞ч醞檣等
    /// 煎霜擊 罹晦縑 濛撩п紫 腆雖 濛撩 塽 匐饜 в蹂
    /// </summary>
    private void ButtonReset()
    {
        _startFilming.SetActive(true);
        _endFilming.SetActive(false);
        _endFilimgButton.interactable = true;
        _printButtonHandler._busy = false;

        _filimgObject.SetActive(true);
        _finishedFilimgObject.SetActive(false);

        // Щ煎斜楚蝶夥 蟾晦
        _progressFillImage.fillAmount = 0;

        // 菴煎陛晦 幗が
        _filmingToSelectCtrl.ButtonActive();
    }

    /// <summary>
    /// 譎艙 謙猿 -> 楚蛤 飛橶褶嘛蚗虞 瞪
    /// 1110 ⑷營 熱薑醞歜
    /// </summary>
    public void PanaelActiveCtrl()
    {
        GameManager.Instance.SetState(KioskState.WaitingForPayment);
        _currentPanel.SetActive(false);
        _changePanel.SetActive(true);
    }
}
